apiVersion: v1
kind: Secret
metadata:
  name: myapp-ingress.lb.lab01.one
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDRENDQXE2Z0F3SUJBZ0lCQlRBS0JnZ3Foa2pPUFFRREF6QmJNUXN3Q1FZRFZRUUdFd0pCVlRFTE1Ba0cKQTFVRUNBd0NibUV4Q3pBSkJnTlZCQWNNQW01aE1Rc3dDUVlEVlFRS0RBSnVZVEVSTUE4R0NTcUdTSWIzRFFFSgpBUllDYm1FeEVqQVFCZ05WQkFNTUNXeGhZakF4TG05dVpUQWVGdzB5TVRBNU1UUXlNalEzTkRaYUZ3MHpNVEE1Ck1USXlNalEzTkRaYU1Hd3hDekFKQmdOVkJBWVRBa0ZWTVFzd0NRWURWUVFJREFKdVlURUxNQWtHQTFVRUJ3d0MKYm1FeEN6QUpCZ05WQkFvTUFtNWhNUkV3RHdZSktvWklodmNOQVFrQkZnSnVZVEVqTUNFR0ExVUVBd3dhYlhsaApjSEF0YVc1bmNtVnpjeTVzWWk1c1lXSXdNUzV2Ym1Vd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUmNhMnozalI0b29vTkQzOHQ0WnZWWG5sU3VGaTcrWlFwQ1RKL3h3amMwcERmNmlFTWNoUjhZVGVVaXhDdHAKNHJrL01kZTZyMHpBcXEzb2hpT3dGQzNxbzRJQlVEQ0NBVXd3Q1FZRFZSMFRCQUl3QURBUkJnbGdoa2dCaHZoQwpBUUVFQkFNQ0JrQXdOQVlKWUlaSUFZYjRRZ0VOQkNjV0pVOVFUbk5sYm5ObElFZGxibVZ5WVhSbFpDQlRaWEoyClpYSWdRMlZ5ZEdsbWFXTmhkR1V3SFFZRFZSME9CQllFRkFZY2M3KzVCMUVKMUYrOXBzTXJ1QnpHVWcwK01JR0QKQmdOVkhTTUVmREI2Z0JUL2lyV2JkNEFncmVuTnRqbkFZV1RYRVdaWE9LRmZwRjB3V3pFTE1Ba0dBMVVFQmhNQwpRVlV4Q3pBSkJnTlZCQWdNQW01aE1Rc3dDUVlEVlFRSERBSnVZVEVMTUFrR0ExVUVDZ3dDYm1FeEVUQVBCZ2txCmhraUc5dzBCQ1FFV0FtNWhNUkl3RUFZRFZRUUREQWxzWVdJd01TNXZibVdDQVFBd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZDQUlDTUFzR0ExVWREd1FFQXdJRm9EQWxCZ05WSFJFRUhqQWNnaHB0ZVdGdwpjQzFwYm1keVpYTnpMbXhpTG14aFlqQXhMbTl1WlRBS0JnZ3Foa2pPUFFRREF3TklBREJGQWlBaTE3RVA4dXZaCmFWTkVSUXpaZWhxU2VJZFlhcnpyR3BvMFA5Z01vYmpkMGdJaEFMaGVCbnNBNmYza1U3TDdrVG9EeVFxT1BTTnYKYU00UmZBUlVVT1dlWGdtZQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUhvU1hvb3llYU9DQUN2ZmhIYk0wRjFTOVVQQSt2TWlVRXQ2UHAydEN5aGVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWEd0czk0MGVLS0tEUTkvTGVHYjFWNTVVcmhZdS9tVUtRa3lmOGNJM05LUTMrb2hESElVZgpHRTNsSXNRcmFlSzVQekhYdXE5TXdLcXQ2SVlqc0JRdDZnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  ingressClassName: avi-lb
  rules:
    - host: myapp-ingress.lb.lab01.one
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 8080
  tls:
    - hosts:
      - myapp-ingress.lb.lab01.one
      secretName: myapp-ingress.lb.lab01.one
